import type { Metadata } from 'next';
import './globals.css';
import { GeistSans } from 'geist/font/sans';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { LogoIconSVG } from '@/components/logo/logo-icon-svg';
import { LogoTitleSVG } from '@/components/logo/logo-title-svg';
import { colors } from '@/constants/colors';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(GeistSans.className, 'text-secondary-foreground')}>
        <div className="flex h-screen w-full bg-[url('/assets/bg-auth.jpeg')]">
          <div className="bg-gradient flex h-full w-full flex-col bg-gradient-to-b from-black/90 via-black/20 to-black/90 ">
            <div className="container z-50 flex h-32 w-full items-center justify-between">
              <div className="flex items-center gap-2">
                <LogoIconSVG width={50} height={50} color={colors.primary} />
                <LogoTitleSVG width={150} height={50} color={colors.primary} />
              </div>
              <Button>Sign In</Button>
            </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
