import type { Metadata } from 'next';
import './globals.css';
import { GeistSans } from 'geist/font/sans';
import { cn } from '@/lib/utils';
import Image from 'next/image';
import { Button } from '@/components/ui/button';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(GeistSans.className, 'text-primary')}>
        <div className="flex h-screen w-full bg-[url('/assets/bg-auth.jpeg')]">
          <div className="bg-gradient flex h-full w-full flex-col bg-gradient-to-b from-black/90 via-black/20 to-black/90 ">
            <div className="container z-50 flex h-32 w-full items-center justify-between">
              <div className="flex items-center gap-2">
                <Image
                  alt="logo"
                  src="/assets/logo.svg"
                  width={48}
                  height={48}
                />
                <Image
                  alt="logo title"
                  src="/assets/logo-title.svg"
                  width={140}
                  height={50}
                />
              </div>
              <Button>Sign In</Button>
            </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
